from core.database.models import Organization, User, OrganizationMember
"""
Domain Ports — Inventory Module
Abstract interfaces (Protocols) for repositories.
"""
from typing import Protocol, List, Optional, Any
from uuid import UUID
from .entities import (
    ProductEntity, StoreEntity, AlertEntity, 
    SalesLogEntity, SupplierEntity, PurchaseOrderEntity
)

class IProductRepository(Protocol):
    async def get_by_id(self, product_id: UUID) -> Optional[ProductEntity]: ...
    async def get_by_sku(self, sku: str, store_ids: List[UUID]) -> List[ProductEntity]: ...
    async def list_by_store(self, store_ids: List[UUID]) -> List[ProductEntity]: ...
    async def save(self, product: ProductEntity) -> ProductEntity: ...
    async def update_settings(self, product_id: UUID, **kwargs) -> Optional[ProductEntity]: ...
    async def delete_by_store(self, store_id: UUID) -> None: ...

class IStoreRepository(Protocol):
    async def get_by_id(self, store_id: UUID) -> Optional[StoreEntity]: ...
    async def list_by_organization(self, org_id: UUID, connected_only: bool = False) -> List[StoreEntity]: ...
    async def get_by_platform(self, org_id: UUID, platform: str) -> Optional[StoreEntity]: ...
    async def save(self, store: StoreEntity) -> StoreEntity: ...

class ISalesLogRepository(Protocol):
    async def list_by_product(self, product_id: UUID, limit: int = 90) -> List[SalesLogEntity]: ...
    async def delete_by_products(self, product_ids: List[UUID]) -> None: ...
    async def save_batch(self, logs: List[SalesLogEntity]) -> None: ...
    async def get_total_sales_for_org(self, org_id: UUID, days: int) -> float: ...

class IAlertRepository(Protocol):
    async def get_by_id(self, alert_id: UUID) -> Optional[AlertEntity]: ...
    async def list_unread(self, store_id: Optional[UUID] = None, org_id: Optional[UUID] = None) -> List[AlertEntity]: ...
    async def save(self, alert: AlertEntity) -> AlertEntity: ...
    async def save_batch(self, alerts: List[AlertEntity]) -> None: ...
    async def mark_as_read(self, alert_id: UUID) -> bool: ...
    async def delete(self, alert_id: UUID) -> bool: ...
    async def exists_unread(self, product_id: UUID, alert_type: str) -> bool: ...

class ISupplierRepository(Protocol):
    async def get_by_id(self, supplier_id: UUID) -> Optional[SupplierEntity]: ...
    async def list_by_store(self, store_id: UUID) -> List[SupplierEntity]: ...
    async def save(self, supplier: SupplierEntity) -> SupplierEntity: ...

class IPurchaseOrderRepository(Protocol):
    async def get_by_id(self, po_id: UUID) -> Optional[PurchaseOrderEntity]: ...
    async def save(self, po: PurchaseOrderEntity) -> PurchaseOrderEntity: ...
    async def list_by_store(self, store_id: UUID) -> List[PurchaseOrderEntity]: ...
