"""add_moq_and_user_prefs

Revision ID: 484034625845
Revises: 945dc776a56e
Create Date: 2026-04-07 22:51:54.645886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '484034625845'
down_revision: Union[str, None] = '945dc776a56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('moq_snapshot', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('predictions', 'moq_snapshot')
    # ### end Alembic commands ###
