"""add_moq_and_user_prefs

Revision ID: 484034625845
Revises: 945dc776a56e
Create Date: 2026-04-07 22:51:54.645886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '484034625845'
down_revision: Union[str, None] = '945dc776a56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('predictions', sa.Column('moq_snapshot', sa.Integer(), nullable=False, server_default='1'))
    # Idempotent: la colonne peut déjà exister si f1a2b3c4d5e6 a tourné en premier
    op.execute("""
        ALTER TABLE users
            ADD COLUMN IF NOT EXISTS preferences JSONB NOT NULL DEFAULT '{}';
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('predictions', 'moq_snapshot')
    # ### end Alembic commands ###
