"""revive_sprint_10_v6

Revision ID: 945dc776a56e
Revises: 003
Create Date: 2026-04-07 22:12:04.538561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945dc776a56e'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('predictions', sa.Column('mape_score', sa.Float(), nullable=True))
    op.drop_column('predictions', 'moq_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('moq_snapshot', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('predictions', 'mape_score')
    op.drop_table('alert_emails')
    # ### end Alembic commands ###
