"""add sprint 12 algorithmic fields

Revision ID: d0ae44df3007
Revises: 484034625845
Create Date: 2026-04-10 01:15:14.015997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ae44df3007'
down_revision: Union[str, None] = '484034625845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('boost_factor', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('products', sa.Column('stock_weight', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_weight')
    op.drop_column('products', 'boost_factor')
    # ### end Alembic commands ###
