"""add_onboarding_fields_to_organization

Revision ID: 172738b967bb
Revises: 7a3e80d22f0c
Create Date: 2026-04-23 18:41:50.301193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172738b967bb'
down_revision: Union[str, None] = '7a3e80d22f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('onboarding_step', sa.String(length=50), nullable=True))
    
    # Fill existing rows
    op.execute("UPDATE organizations SET onboarding_completed = false WHERE onboarding_completed IS NULL")
    op.execute("UPDATE organizations SET onboarding_step = 'welcome' WHERE onboarding_step IS NULL")
    
    # Set NOT NULL
    op.alter_column('organizations', 'onboarding_completed', nullable=False)
    op.alter_column('organizations', 'onboarding_step', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'onboarding_step')
    op.drop_column('organizations', 'onboarding_completed')
    # ### end Alembic commands ###
