"""add_org_settings

Revision ID: 1cd541e49737
Revises: ee3977eb7e36
Create Date: 2026-04-13 15:47:22.963587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cd541e49737'
down_revision: Union[str, None] = 'ee3977eb7e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable
    op.add_column('organizations', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # 2. Update existing rows with a default empty JSON object
    op.execute("UPDATE organizations SET settings = '{}' WHERE settings IS NULL")
    
    # 3. Alter column to be NOT NULL
    op.alter_column('organizations', 'settings', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'settings')
    # ### end Alembic commands ###
