"""add_stripe_subscription_id

Revision ID: 6f1cf0ef2f1a
Revises: 712760d34a40
Create Date: 2026-04-25 13:01:13.945717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f1cf0ef2f1a'
down_revision: Union[str, None] = '712760d34a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'recovery_codes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'recovery_codes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('organizations', 'stripe_subscription_id')
    # ### end Alembic commands ###
