"""add_inventory_level_to_cleaned_demand

Revision ID: 73e9803b4e73
Revises: 5f512f6e157d
Create Date: 2026-04-13 21:49:09.484952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e9803b4e73'
down_revision: Union[str, None] = '5f512f6e157d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleaned_demand', sa.Column('inventory_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cleaned_demand', 'inventory_level')
    # ### end Alembic commands ###
