"""Add source_connections table

Revision ID: a5941d116ac9
Revises: d0ae44df3007
Create Date: 2026-04-10 23:35:36.181278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5941d116ac9'
down_revision: Union[str, None] = 'd0ae44df3007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE source_connections (
            id UUID NOT NULL, 
            shop_id UUID NOT NULL, 
            platform platformsource NOT NULL, 
            connected BOOLEAN NOT NULL, 
            last_sync_at TIMESTAMP WITHOUT TIME ZONE, 
            health_status VARCHAR(50), 
            PRIMARY KEY (id)
        )
    """)
    op.create_index(op.f('ix_source_connections_shop_id'), 'source_connections', ['shop_id'], unique=False)
    op.drop_constraint('alert_emails_product_id_fkey', 'alert_emails', type_='foreignkey')
    op.create_foreign_key(None, 'alert_emails', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False) # Already exists probably
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_constraint(None, 'alert_emails', type_='foreignkey')
    op.create_foreign_key('alert_emails_product_id_fkey', 'alert_emails', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_source_connections_shop_id'), table_name='source_connections')
    op.drop_table('source_connections')
    # ### end Alembic commands ###
