"""add_lead_time_sigma

Revision ID: e49c6b8e7bfc
Revises: 1bbc9f8f6faf
Create Date: 2026-04-15 17:01:06.424975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49c6b8e7bfc'
down_revision: Union[str, None] = '1bbc9f8f6faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('demand_sigma', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('lead_time_sigma', sa.Float(), nullable=True))
    op.drop_index('ix_users_shop_id', table_name='users')
    op.drop_column('users', 'shop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_users_shop_id', 'users', ['shop_id'], unique=False)
    op.drop_column('suppliers', 'lead_time_sigma')
    op.drop_column('predictions', 'demand_sigma')
    # ### end Alembic commands ###
