"""add_trial_ends_at

Revision ID: e68ec673a334
Revises: 9e10f536c2be
Create Date: 2026-05-12 23:11:44.061973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68ec673a334'
down_revision: Union[str, None] = '9e10f536c2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'trial_ends_at')
    # ### end Alembic commands ###
