"""add_invitations_table

Revision ID: ee3977eb7e36
Revises: a5941d116ac9
Create Date: 2026-04-13 11:53:40.768862

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ee3977eb7e36'
down_revision: Union[str, None] = 'a5941d116ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ENUM types sont créés dans f1a2b3c4d5e6 avec les valeurs lowercase correctes
    # Les DO blocks ci-dessous sont des no-op si les types existent déjà
    op.execute("DO $$ BEGIN CREATE TYPE userrole AS ENUM ('admin', 'manager', 'viewer'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE invitationstatus AS ENUM ('pending', 'accepted', 'expired'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    # Idempotent : ne plante pas si seed_v2 a déjà créé la table
    op.execute("""
        CREATE TABLE IF NOT EXISTS invitations (
            id              UUID         NOT NULL DEFAULT gen_random_uuid(),
            email           VARCHAR(255) NOT NULL,
            organization_id UUID         NOT NULL,
            role            userrole     NOT NULL DEFAULT 'viewer',
            code            VARCHAR(64)  NOT NULL,
            status          invitationstatus NOT NULL DEFAULT 'pending',
            invited_by_id   UUID,
            created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
            expires_at      TIMESTAMP    NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
            FOREIGN KEY (invited_by_id)   REFERENCES users (id)
        );
    """)
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_invitations_code  ON invitations (code);")
    op.execute("CREATE INDEX        IF NOT EXISTS ix_invitations_email ON invitations (email);")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_org_platform', 'stores', type_='unique')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_code'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
